#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Mar 07 16:22:19 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=MakeUp-UltraFast-9.3e.zip
enableShaders=false
